### ISSUE TITLE
THORS - positionalUncertainty defined as DatatypeProperty

### ISSUE THREAD

**Issue by mdesalvo** [CGI-IUGS/timescale-ont#10]
Hi,
in the [THORS](https://github.com/CGI-IUGS/timescale-ont/blob/master/rdf/thors.ttl) ontology the property "thors:positionalUncertainty" is declared as a datatype property having range "time:Duration". Shouldn't it be declared as an object property, like its counterpart in [GTS](https://github.com/CGI-IUGS/timescale-ont/blob/master/rdf/gts.ttl) ontology? In fact "time:Duration" is a class, not a datatype, with its domain properties "time:numericDuration" and "time:unitType". 

If this is by design, can you kindly provide an example of usage of this property as a datatype property?

Regards,
Marco

**Comment by dr-shorthair** [comment]
@mdesalvo you are correct. 
I will fix it.

**Comment by dr-shorthair** [comment]
Fixed with https://github.com/CGI-IUGS/timescale-ont/pull/11
